version: '3.0'

services:
  api:
    build: .
    image: wselfjes/ds9_api
    volumes:
      - /etc/hosts:/etc/hosts:ro
  front:
    build: front
    image: wselfjes/ds9_front
    ports:
      - 8080:8080
